# LOGS and Monitoring ==========================================================================================

- name: Install ELK
  hosts: elk_server
  become: yes
  roles:
    - { role: 'elk', tags: 'elk' }

